Consolidate to just Amplify Canaries for Testing

diff --git a/.github/composite_actions/log_metric/action.yaml b/.github/composite_actions/log_metric/action.yaml
--- a/.github/composite_actions/log_metric/action.yaml
+++ b/.github/composite_actions/log_metric/action.yaml
@@ -1,5 +1,5 @@
 name: Log Metric
-description: Log data point to a metric with the provided value. If the metric is not there, it will create one
+description: Log data point to a metric with the provided value. If the metric is not there, it will create one.
 # To avoid 'Credentials could not be loaded' calling workflows must include:
 # permissions:
 #  id-token: write
@@ -7,23 +7,65 @@ description: Log data point to a metric with the provided value. If the metric i
 inputs:
   aws-region:
     required: true
-    description: The AWS region
+    description: The AWS region.
   role-to-assume:
     required: true
-    description: The role to assume in the STS session
-  metric-name:
-    description: Name of the metric to track in Cloudwatch.
-    required: true
-  value:
+    description: The role to assume in the STS session.
+
+  #value:
     # Why we publish value 0 on success: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html#publishingZero
-    description: Value of the metric to track in Cloudwatch.
+   # description: Value of the metric to track in Cloudwatch.
+#    required: true
+
+  # Global Metric Dimensions 
+  testType:
+    description: canary, integration, unit testType.
     required: true
-  dimensions:
-    description: Dimensions of metric to track in Cloudwatch, in format dimensionName1=value,dimensionName2=value,...
+  category:
+    description: analytics, api, authenticator, etc. 
+    required: true
+  workflowName: 
+    description: The Github Action workflow.yaml file name.  ie "AmplifyCanaries".
+    required: true 
+  # failingStep: Look into getting via code 
+
+
+  # FlutterDart Workflows Metric Dimensions 
+  framework:
+    description: flutter, dart. 
     required: false
+  flutterDartChannel:
+    description: beta, stable. 
+    required: false
+  dartVersion: 
+    description: 3, 2.19, 2.18, etc. 
+    required: false
+  flutterVersion:
+    description: 3.10.6, 3.10.5, etc. 
+    required: false
+  dartCompiler:
+    description: dart2js, ddc, dart, dart2wasm.
+    required: false
+
+  # Platform Workflows Metric Dimensions
+  platform:
+    description: android, ios, web, linux, windows.
+    required: false
+  platformVersion: 
+    description: ios-14.5, ios-16, android-25-x86, etc. 
+    required: false 
+
 runs:
   using: 'composite'
   steps:
+    #- name: Exit if not scheduled
+   #   shell: bash
+    #  run: |
+    #    if [ "${{ github.event_name }}" != "schedule" ]; then
+    #      echo "This was not triggered by a schedule, exiting."
+    #      exit 1
+    #    fi
+
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # 1.7.0
       with:
@@ -31,7 +73,44 @@ runs:
         aws-region: ${{ inputs.aws-region }}
         role-duration-seconds: 900
 
+    - name: GitHub Actions job_id parser
+      uses: Tiryoh/gha-jobid-action@v0.1.2
+      id: jobs
+      with:
+        github_token: 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 #${{ secrets.GITHUB_TOKEN }}
+        job_name: ${{ github.job }}
+
+    - name: Get Failing Step
+      if: env.didFail
+      shell: bash
+      run: |
+      response=$(curl -s -H "Authorization: token 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 \
+        -H "Accept: application/vnd.github.v3+json" \
+        "https://api.github.com/repos/aws-amplify/amplify-flutter/actions/jobs/${{ steps.jobs.outputs.job_id }}")
+        failing_step_name=$(echo "$response" | jq -r '.steps[] | select(.conclusion == "failure") | .name')
+
+        if [ "$conclusion" == "failure" ]; then
+          echo "IS_FAILED=true" >> $GITHUB_ENV
+        else
+          echo "IS_FAILED=false" >> $GITHUB_ENV
+        fi
+
+        echo "FAILING_STEP=$failing_step" >> $GITHUB_ENV
+
     - name: Run Dart script
       # Run a Dart script to put metric data.
-      run: dart ./tool/send_metric_data.dart ${{ inputs.metric-name }} ${{ inputs.value }} ${{ inputs.dimensions }}
+      run: dart ./tool/send_metric_data.dart \
+        github_metric_1.0 \
+        ${{ env.IS_FAILED }} \
+        ${{ inputs.testType }} \
+        ${{ inputs.category }} \
+        ${{ inputs.workflowName }} \
+        ${{ inputs.framework }} \
+        ${{ inputs.flutterDartChannel }} \
+        ${{ inputs.dartVersion }} \
+        ${{ inputs.flutterVersion }} \
+        ${{ inputs.dartCompiler }} \
+        ${{ inputs.platform }} \
+        ${{ inputs.platformVersion }} \
+        ${{ env.FAILING_STEP }}
       shell: bash
